### ISSUE TITLE
stop factoid carousel

### ISSUE THREAD

**Issue by isc-rsingh** [AccessibleOlli/ces-stop-arrivals#5]
Right now stop description in StopHeader is static. It should use the `REACT_APP_OLLI_STOP_IDX` environment variable to select a stop feature out of stops.json (just like olli-stop does). It should then choose an image to display based on that (image names can be suffixed with the index, e.g. `olli-stop-info-image-IDX.jpg`. Finally it should also display the array of factoids in a carousel below the image.

**Comment by markwatsonatx** [comment]
StopHeader is being passed the stop, so I'm not sure if this is still an issue. The image is not displayed, however I am not sure where it should be displayed.
